import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Nav from "./components/nav";
import { Logo } from "./components/icons/Logo";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${jost.className} flex justify-center items-center min-h-screen`}>
        <div className="my-[30px] mx-auto flex justify-between max-w-[1440px] w-[calc(100vw-187px)] relative">
          <div className="flex flex-col gap-[80px]">
            <Logo />
            <Nav />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
